---
- name: enable mod_{{item}}
  sudo: yes
  command: a2enmod {{item}}
  register: command_result
  changed_when: "'already enabled' not in command_result.stdout"
  notify:
    - restart apache
  with_items: apache_mods_enabled

- name: disable mod_{{item}}
  sudo: yes
  command: a2dismod {{item}}
  register: command_result
  changed_when: "'already disabled' not in command_result.stdout"
  notify:
    - restart apache
  with_items: apache_mods_disabled

- name: ensure apache is running (and enable it at boot)
  sudo: yes
  service: name={{apache_service_name}} state=started enabled=yes
  when: not (is_integration_test is defined and is_integration_test and
      (ansible_os_family == "RedHat" or
       (ansible_distribution == "Debian" and
        ansible_distribution_major_version == "9") or
       (ansible_distribution == "Debian" and
        ansible_distribution_major_version == "stretch/sid") or
       (ansible_distribution == "Ubuntu" and
        ansible_distribution_major_version == "16")
      ))


